name: jp_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  widget_mask: ^1.0.0+0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/backgrounds/
    - assets/details/
    - assets/images/
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/sf_pro_fonts/SF-Pro-Display-Ultralight.otf
          weight: 100
        - asset: assets/sf_pro_fonts/SF-Pro-Display-UltralightItalic.otf
          weight: 100
          style: italic
        - asset: assets/sf_pro_fonts/SF-Pro-Display-Thin.otf
          weight: 200
        - asset: assets/sf_pro_fonts/SF-Pro-Display-ThinItalic.otf
          weight: 200
          style: italic
        - asset: assets/sf_pro_fonts/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/sf_pro_fonts/SF-Pro-Display-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/sf_pro_fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/sf_pro_fonts/SF-Pro-Display-RegularItalic.otf
          weight: 400
          style: italic
        - asset: assets/sf_pro_fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/sf_pro_fonts/SF-Pro-Display-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/sf_pro_fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/sf_pro_fonts/SF-Pro-Display-SemiboldItalic.otf
          weight: 600
          style: italic
        - asset: assets/sf_pro_fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/sf_pro_fonts/SF-Pro-Display-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/sf_pro_fonts/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: assets/sf_pro_fonts/SF-Pro-Display-HeavyItalic.otf
          weight: 800
          style: italic
        - asset: assets/sf_pro_fonts/SF-Pro-Display-Black.otf
          weight: 900
        - asset: assets/sf_pro_fonts/SF-Pro-Display-BlackItalic.otf
          weight: 900
          style: italic

    - family: SFProText
      fonts:
        - asset: assets/sf_pro_fonts/SF-Pro-Text-Ultralight.otf
          weight: 100
        - asset: assets/sf_pro_fonts/SF-Pro-Text-UltralightItalic.otf
          weight: 100
          style: italic
        - asset: assets/sf_pro_fonts/SF-Pro-Text-Thin.otf
          weight: 200
        - asset: assets/sf_pro_fonts/SF-Pro-Text-ThinItalic.otf
          weight: 200
          style: italic
        - asset: assets/sf_pro_fonts/SF-Pro-Text-Light.otf
          weight: 300
        - asset: assets/sf_pro_fonts/SF-Pro-Text-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/sf_pro_fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/sf_pro_fonts/SF-Pro-Text-RegularItalic.otf
          weight: 400
          style: italic
        - asset: assets/sf_pro_fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/sf_pro_fonts/SF-Pro-Text-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/sf_pro_fonts/SF-Pro-Text-Semibold.otf
          weight: 600
        - asset: assets/sf_pro_fonts/SF-Pro-Text-SemiboldItalic.otf
          weight: 600
          style: italic
        - asset: assets/sf_pro_fonts/SF-Pro-Text-Bold.otf
          weight: 700
        - asset: assets/sf_pro_fonts/SF-Pro-Text-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/sf_pro_fonts/SF-Pro-Text-Heavy.otf
          weight: 800
        - asset: assets/sf_pro_fonts/SF-Pro-Text-HeavyItalic.otf
          weight: 800
          style: italic
        - asset: assets/sf_pro_fonts/SF-Pro-Text-Black.otf
          weight: 900
        - asset: assets/sf_pro_fonts/SF-Pro-Text-BlackItalic.otf
          weight: 900
          style: italic

    - family: SFProRounded
      fonts:
        - asset: assets/sf_pro_fonts/SF-Pro-Rounded-Ultralight.otf
          weight: 100
        - asset: assets/sf_pro_fonts/SF-Pro-Rounded-Thin.otf
          weight: 200
        - asset: assets/sf_pro_fonts/SF-Pro-Rounded-Light.otf
          weight: 300
        - asset: assets/sf_pro_fonts/SF-Pro-Rounded-Regular.otf
          weight: 400
        - asset: assets/sf_pro_fonts/SF-Pro-Rounded-Medium.otf
          weight: 500
        - asset: assets/sf_pro_fonts/SF-Pro-Rounded-Semibold.otf
          weight: 600
        - asset: assets/sf_pro_fonts/SF-Pro-Rounded-Bold.otf
          weight: 700
        - asset: assets/sf_pro_fonts/SF-Pro-Rounded-Heavy.otf
          weight: 800
        - asset: assets/sf_pro_fonts/SF-Pro-Rounded-Black.otf
          weight: 900